# Generated by Django 4.2.4 on 2023-11-10 12:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_alter_post_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(editable=False, verbose_name=datetime.datetime(2023, 11, 10, 12, 57, 39, 852882, tzinfo=datetime.timezone.utc)),
        ),
    ]
