# Generated by Django 4.2.4 on 2023-11-12 13:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 12, 13, 57, 3, 844083, tzinfo=datetime.timezone.utc)),
        ),
    ]
