# Generated by Django 4.2.4 on 2023-11-12 14:06

from django.db import migrations, models
import network.models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0013_alter_post_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=network.models.generate_unique_filename),
        ),
    ]
